apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app-unir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: alucardforever/todo-app:v1.0
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI