---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-unir
  namespace: todo-app-unir
spec:
  type: LoadBalancer
  selector:
    app: todo-app-unir
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    -192.168.1.100